name: CI
env:
    GITHUB_TOKEN: 28ede5d9c3d270efc1574979046df25052ae621d
    COMMIT_MSG: |
      commit message
      skip-checks: true
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        pwd
        echo test, and deploy your project. 
        git config --local user.email "ankit85jsin@yahoo.co.in"
        git config --local user.name "ankit85jsin"       
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/anki-org/repo2.git
        # Checkout the branch so we can push back to it
        #git checkout -b testuser
        git add --all
        git commit --allow-empty -m "${COMMIT_MSG}"
        git show-ref
        git push origin testuser

